# This configuration is intended for development purposes, it's **your** responsibility to harden it for production
name: bdqm
services:
  redis:
    image: redis:7-alpine
    container_name: ankataa-redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis-data-bqdm:/data
