# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: bdqm
services:
  mysql:
    extends:
      file: mysql.yml
      service: mysql
  informix:
    extends:
      file: ./informix.yml
      service: informix
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  redis:
    extends:
      file: ./redis.yml
      service: redis
volumes:
  redis-data-bqdm:
  informix-data:
