spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/bank_data_quality?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: Bamako@2209
      driver-class-name: com.mysql.cj.jdbc.Driver

    informix:
      # JDBC Direct (recommandé pour Java 17+)
      jdbc-url: jdbc:informix-sqli://10.3.0.66:1526/bdmsa:INFORMIXSERVER=ol_bdmsa;DELIMIDENT=Y;DB_LOCALE=en_US.utf8;CLIENT_LOCALE=en_US.utf8
      username: bank
      password: bank
      driver-class-name: com.informix.jdbc.IfxDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

app:
  jwt:
    secret: bank_data_quality_secret_key_2024_change_in_production
    expiration: 86400000
  features:
    ldap-authentication: false
    informix-integration: true  # Activer Informix si disponible
    workflow-automation: true
    rpa-integration: false  # UiPath non configuré localement
    kpi-tracking: true
