spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/bdqm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: bdqm
      password: bdqm

    informix:
      jdbc-url: jdbc:odbc:lcb
      username: bank
      password: bank

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    drop-first: true
    contexts: dev

app:
  jwt:
    secret: bank_data_quality_secret_key_2024_change_in_production
    expiration: 86400000
  features:
    ldap-authentication: false
